### PR TITLE
add GitHub Actions testing

### PR DESCRIPTION
**Pull request by ocefpaf**
This probably won't pass in the first iteration but let's see how far we can go trying to get the tests to run again.

### CODE REVIEW

**Comment by davidovitch** [comment]
I assume this PR will fix #52.

Looks pretty good to me but I don't have any experience with the Github/Travis build/test environment.

**Comment by ocefpaf** [comment]
> I assume this PR will fix #52.

Yes. That fix is included.

> Looks pretty good to me but I don't have any experience with the Github/Travis build/test environment.

I'll probably iterate more after this is merged this one is ready for a review and merge. Let me know if you want to add some extra comments on what this is doing.

**Review by morbult — COMMENTED** [review]
mpmath and pytest are also required to be able to run the tests

**Comment by morbult** [comment]
My bad, missed that file.

I have no experience with Actions testing, or Travis for that matter, but it looks really neat. Out of curiosity, is this a separate approach to run testing than the existing .travis.yml? Is the plan to use Actions for building as well?

**Comment by ocefpaf** [comment]
> I have no experience with Actions testing, or Travis for that matter, but it looks really neat. Out of curiosity, is this a separate approach to run testing than the existing .travis.yml? Is the plan to use Actions for building as well?

The plan is to remove Travis-CI and substitute it with GitHub Actions. Travis-CI was the state of the art for CI testing but since it was sold to another company the OSS service is really degraded and unreliable. GitHub Actions is faster, more flexible, and seems to be the new OSS standard.

**Comment by ocefpaf** [comment]
The CIs results can be viewed at https://github.com/ocefpaf/pywafo/actions/runs/3643452287/jobs/6151687789

Once merge they'll also run here on every PR. Things that are still missing but I cannot fix them at the moment:

- [ ] Add Windows to the build matrix
- [ ] Fix the macOS compilation on py>3.7
- [ ] Fix the 1-2 failures that are happening on some of the matrix items `test_to_t_pdf` (all of them) and `test_bk_regression_with_beta` (some py version only)

This is as far as I can take this PR. I can investigate more the macOS builds and Windows compilation later but I'm clueless to the failures and if they are relevant or just bad expected results due to different scipy versions.

**Comment by Gjacquenot** [comment]
It would be nice to merge this pull request!

**Comment by davidovitch** [comment]
Thanks for the reminder. I will have a look this weekend and merge.

**Pull request merged**
