### PR TITLE
Bug fix in plot_wave and fixed tutorials

### PR DESCRIPTION
**Pull request by eelcovv**
Hi, 
I have merge my fixes with the current master. I am getting an able to merge message now, hopefully you can use it now
Regards
Eelco

### CODE REVIEW

**Comment by eelcovv** [comment]
I am not sure everything was fine last time because the directory structure changed a bit. I can now run the tutorials on my machine. Adding another pull request, to see if it works now

**Comment by pbrod** [comment]
Hi, thanks for the contribution. However, this pullrequest needs to be rebased and cleaned up a bit before inclusion into wafo.

**Comment by eelcovv** [comment]
Hi Per,

Ok, I will look at that, but I am quite busy at the moment. With cleaned
you me write down a bit cleaner. Rebase as in: merge with the latest
version of pywafo?

2016-06-29 0:39 GMT+02:00 Per A. Brodtkorb <notifications@github.com>:

**Comment by pbrod** [comment]
Yes, merge with the latest version.

**Comment by eelcovv** [comment]
I will do

**Pull request closed without merging**
