### PR TITLE
Scipy

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR fixes:

- Invalid encoding `mbcs`
- `scipy.lib` import

It also moves the code one level down and adds a `README.rst`

These changes make it easier to package and install wafo.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@davidovitch Note the the package name is `pywafo`, while that module name (what we import) is just `wafo`.  That is OK, but it can be confusing to newbies, and some "dumb" tools.  Conda, for example, does not list `pywafo` in its automate `environment.yml` file because it thinks `pywafo` does not exist.  It will add a `pip install wafo` instead (which also does not exits).

Consider renaming the module to `pywafo` or the package to `wafo`.  Note the the project name can still be `pywafo` in both scenarios, to avoid classing names with the matlab wafo.

For example the [`python-gsw`](https://github.com/TEOS-10/python-gsw) project names its package and module `gsw`.  A direct relation to the matlab counterpart, but with a different project name.

**Comment by davidovitch** [comment]
@pbrod, I what do you think about renaming the package to wafo (while keeping the project name pywafo)? Or do you prefer package and project name to be the same, being pywafo?
Do you have an opinion regarding re-organizing the directory structure so instead of ```pywafo/src/wafo/*``` we just have ```wafo/*```, and also move ```pywafo/src/wafo/doc``` to ```doc``` (so it is similar to projects such as ```numpy```.

**Comment by pbrod** [comment]
It is ok for me to rename the package to wafo and keep the project as pywafo.

For the https://github.com/pbrod/numdifftools project I have used pyscaffold to organize the project.
(http://pyscaffold.readthedocs.org)

My plan is to update wafo to follow the pyscaffold strategy when it comes to packaging.
The structure will then be
wafo/docs
wafo/tests
wafo/wafo
wafo/wafo/covariance
wafo/wafo/spectrum
wafo/wafo/stats
wafo/wafo/transform
...

If somebody wants to do this transition, that would be perfect.

**Comment by ocefpaf** [comment]
> My plan is to update wafo to follow the pyscaffold strategy

:+1: 

However, I believe that should be done in a separate PR.  This PR one fixes a bug and move the directory down 1-level.  The latter may be interpreted as step 0 towards those goals.

**Comment by davidovitch** [comment]
@ocefpaf agreed, this PR should only contain the bug fix. We'll use the ```pyscaffold```approach to re-organize the module. You're welcome to sent in a new PR for that, otherwise I will have some time somewhere in this or next week.

**Comment by ocefpaf** [comment]
> @ocefpaf agreed, this PR should only contain the bug fix.

This wasn't exactly what I meant.  Moving the code 1 level down and adding the README allowed for immediate packaging while adding very little noise to the bug fix.

Anyway. I remove the last two commits and reduced this PR to the bug fix.

**Comment by pbrod** [comment]
This seems ok. Merging the PR.

**Pull request merged**
