### PR TITLE
Fix import pade for scipy>=1.0.0

### PR DESCRIPTION
**Pull request by morbult**
pade has moved to scipy.interpolate in scipy 1.0.0, both imports kept to not break for scipy<1

### CODE REVIEW

**Comment by davidovitch** [comment]
Thanks! Do you mind adding `pade has moved to scipy.interpolate in scipy 1.0.0` just to make it clear why it is done?

**Comment by morbult** [comment]
Do you mean as a comment in the code?

**Comment by davidovitch** [comment]
Yes, that would help in this particular case with the readability of the code.

**Comment by morbult** [comment]
Comment added in this and #46

**Comment by pbrod** [comment]
Looks good to me. Closing

**Pull request merged**
